### ISSUE TITLE
The number of parameters

### ISSUE THREAD

**Issue by vinhtran1** [fsx950223/MobilenetV3#2]
I am so confused when I have a summary of MobileNetv3
![image](https://user-images.githubusercontent.com/28581311/66995568-714e7180-f0f9-11e9-8650-0be68d1f847d.png)
The result is 
![image](https://user-images.githubusercontent.com/28581311/66994880-3992fa00-f0f8-11e9-83a0-71da15a9b18f.png)
The number of parameters is less than 1 million compare with the original paper's result (2.9 million)
![image](https://user-images.githubusercontent.com/28581311/66995726-aeb2ff00-f0f9-11e9-8644-75da9d735c12.png)

May I wrong in somewhere?
p/s: sorry for a little mistake, I changed "model" into "model_mobilnetv3" for some test and I forgot to fix it

**Comment by fsx950223** [comment]
NUM_CLASSES causes the problem

**Comment by vinhtran1** [comment]
Thanks a lot

**Comment by zclyaya** [comment]
![image](https://github.com/fsx950223/MobilenetV3/assets/88328796/1bd73d61-4040-4a17-a6b3-34ea6fae3fb9)
Why is it not 2.9M in the table in the article?
![image](https://github.com/fsx950223/MobilenetV3/assets/88328796/d0c1d046-3782-4476-b64d-62ac8574cd62)
![image](https://github.com/fsx950223/MobilenetV3/assets/88328796/37ef164a-e970-4fda-838b-dd715c081dba)

May I wrong in somewhere?
